Repository ezcode-my/frontend, pull requests merged in 2025-07, with the labels that each got.

#29 feat : discussions 의 토론글, 댓글, 대댓글 crud 기능
  src/features/problem/ui/Tabs/DetailProblem.tsx
  src/features/problem/ui/Tabs/Discussions/DiscussionContent.tsx
  src/features/problem/ui/Tabs/Discussions/Replies.tsx
  src/features/problem/ui/Tabs/Discussions/ShowChildReplies.tsx
  src/features/problem/ui/Tabs/Discussions/Vote.tsx
  src/features/problem/ui/Tabs/nestedReplies/NestedReply.tsx
  src/features/problem/ui/Tabs/nestedReplies/index.tsx
  src/features/problem/ui/Tabs/replies/Reply.tsx
  src/features/problem/ui/Tabs/replies/index.tsx
  src/query/discussions/index.ts
  src/query/discussions/replies/replies.mutation.ts
  src/query/discussions/replies/replies.mutation.types.ts
  src/query/discussions/replies/replies.query.ts
  src/query/discussions/replies/replies.query.types.ts
  src/query/discussions/vote.ts
  src/query/discussions/vote/vote.ts
  src/query/discussions/vote/vote.type.ts
Labels: feat

#30 문제 리스트 검색어 필터, 마이페이지
  src/api/constants/api.constants.ts
  src/app/(auth)/(navigationsBarLayout)/mypage/Heatmap.tsx
  src/app/(auth)/(navigationsBarLayout)/mypage/SideNavigation.tsx
  src/app/(auth)/(navigationsBarLayout)/mypage/page.tsx
  src/app/(auth)/(navigationsBarLayout)/mypage/tab/ChangePassword.tsx
  src/app/(auth)/(navigationsBarLayout)/mypage/tab/Mine.tsx
  src/app/(auth)/(navigationsBarLayout)/mypage/tab/Solved.tsx
  src/app/(auth)/(navigationsBarLayout)/mypage/ui/Heatmap.tsx
  src/app/(auth)/(navigationsBarLayout)/mypage/ui/SolvedModal.tsx
  src/app/(auth)/(navigationsBarLayout)/problems/page.tsx
  src/app/(auth)/(navigationsBarLayout)/problems/ui/Table.tsx
  src/app/layout.tsx
  src/query/mypage/mypage.interface.ts
  src/query/mypage/mypage.ts
  src/query/problem/problem.interface.ts
  src/query/problem/problems.ts
Labels: feat

#37 feat: 랜딩페이지 이번주 top10 데이터 패칭
  src/api/constants/api.constants.ts
  src/app/(auth)/(navigationsBarLayout)/page.tsx
  src/entities/rankings/actions/getRankings.actions.ts
  src/entities/rankings/actions/getRankings.actions.types.ts
  src/entities/rankings/ui/Rankings.tsx
Labels: feat

#40 refactoring : chat 기능 부분 리팩토링
  src/app/(auth)/(navigationsBarLayout)/@chatDialog/(.)chat/page.tsx
  src/app/(auth)/(navigationsBarLayout)/@chatDialog/page.tsx
  src/app/(auth)/(navigationsBarLayout)/chat/page.tsx
  src/app/(auth)/(navigationsBarLayout)/page.tsx
  src/app/globals.css
  src/constants/paths.ts
  src/features/chat/hooks/socket/useJoinChatRoom.ts
  src/features/chat/hooks/useChatDialogTrigger.ts
  src/features/chat/index.ts
  src/features/chat/ui/ChatDialogOpenButton.tsx
  src/features/chat/ui/ChatRoomItem.tsx
  src/features/chat/ui/ChatRoomList.tsx
  src/features/chat/ui/ChatTriggerButton.tsx
  src/features/chat/ui/CreateChatRoomButton.tsx
  src/features/chat/ui/CreateChatRoomDialog.tsx
  src/features/chat/ui/chatRoom/ChatInput.tsx
  src/features/chat/ui/chatRoom/ChatRoomHeader.tsx
  src/features/chat/ui/chatRoom/index.tsx
  src/features/chat/ui/chatRoomList/ChatRoomItem.tsx
  src/features/chat/ui/chatRoomList/ChatSearchBar.tsx
  src/features/chat/ui/chatRoomList/index.tsx
Labels: style, refactoring

#41 feat : header
  public/icons/code.svg
  public/icons/trophy.svg
  public/icons/user.svg
  public/logo/navigationEzCodeLogo.svg
  src/app/(auth)/(navigationsBarLayout)/layout.tsx
  src/app/layout.tsx
  src/shared/ui/linkedButton/index.tsx
  src/widgets/NavigationBar/UserSelect.tsx
  src/widgets/NavigationBar/index.tsx
  src/widgets/navigation-bar/index.tsx
  src/widgets/navigation-bar/ui/NavigationBar.tsx
Labels: feat, style

#48 refactoring : landing page
  public/icons/star.svg
  public/icons/target.svg
  public/logo/EZMainLogo.svg
  public/logo/EzCodeLogo.svg
  src/api/constants/api.constants.ts
  src/app/(auth)/(navigationsBarLayout)/page.tsx
  src/app/globals.css
  src/entities/auth/model/mutation/auth.mutation.ts
  src/entities/rankings/actions/getRankings.actions.ts
  src/entities/rankings/actions/getRankings.actions.types.ts
  src/entities/rankings/ui/RankingItem.tsx
  src/entities/rankings/ui/Rankings.tsx
  src/widgets/landingCTA/index.tsx
  src/widgets/landingCTA/ui/StartButton.tsx
Labels: feat, style, refactoring

#49 refactor : header
  src/app/layout.tsx
  src/widgets/NavigationBar/UserSelect.tsx
  src/widgets/NavigationBar/navigateAttribute.ts
  src/widgets/NavigationBar/ui/AuthActions.tsx
  src/widgets/NavigationBar/ui/Notifications.tsx
  src/widgets/NavigationBar/ui/index.tsx
Labels: feat, style, refactoring

#51 문제 리스트 페이지 퍼블 수정
  src/app/(auth)/(navigationsBarLayout)/problems/page.tsx
  src/app/(auth)/(navigationsBarLayout)/problems/ui/Table.tsx
  src/shared/ui/button/Button.tsx
  src/shared/ui/select/Select.tsx
Labels: feat, style, refactoring

#54 마이페이지 디자인 변경
  public/icons/mypage/bookopen.svg
  public/icons/mypage/mail.svg
  public/icons/mypage/mine.svg
  public/icons/mypage/password.svg
  public/icons/mypage/passwordGreen.svg
  public/icons/mypage/report.svg
  src/api/constants/api.constants.ts
  src/app/(auth)/(navigationsBarLayout)/mypage/SideNavigation.tsx
  src/app/(auth)/(navigationsBarLayout)/mypage/page.tsx
  src/app/(auth)/(navigationsBarLayout)/mypage/tab/ChangePassword.tsx
  src/app/(auth)/(navigationsBarLayout)/mypage/tab/Mine.tsx
  src/app/(auth)/(navigationsBarLayout)/mypage/tab/Solved.tsx
  src/app/(auth)/(navigationsBarLayout)/mypage/ui/Heatmap.tsx
  src/entities/mypage/model/query.ts
  src/entities/mypage/model/types.ts
Labels: feat, style, refactoring
