Repository ezcode-my/frontend, pull requests merged in 2025-09, with the labels that each got.

#113 Feat : mark down
  package.json
  pnpm-lock.yaml
  src/entities/problem/ui/DetailProblem.tsx
  src/features/submitCode/submission/ui/TerminalOutput/CodeReviewSummary.tsx
  src/shared/mdx/MdxRenderer.tsx
  src/shared/ui/FormatMarkdown.tsx
Labels: feat

#124 [Fix] problem submit & problem git push
  src/app/(auth)/(navigationsBarLayout)/layout.tsx
  src/app/(auth)/(navigationsBarLayout)/problems/[problemId]/page.tsx
  src/entities/submitCode/gitpush/actions/getGitHub.ts
  src/entities/submitCode/gitpush/model/query/gitpush.query.ts
  src/entities/submitCode/index.ts
  src/entities/submitCode/submission/model/query/submitCode.query.ts
  src/features/discussions/reply/ui/Replies.tsx
  src/features/submitCode/gitPush/ui/GitPushDialog.tsx
  src/features/submitCode/submission/hooks/useConnectProblemWebSocket.ts
  src/features/submitCode/submission/ui/ProblemWorksSection.tsx
  src/features/submitCode/submission/ui/TerminalOutput/CodeResultSummary.tsx
  src/features/submitCode/submission/ui/TerminalPanel.tsx
  src/widgets/globalFloatingWidget/ui/index.tsx
Labels: fix, refactoring

#126 [Fix] code editor 수정, build 에러 수정
  src/app/(auth)/(navigationsBarLayout)/mypage/page.tsx
  src/app/(auth)/(navigationsBarLayout)/mypage/tab/Solved.tsx
  src/app/globals.css
  src/entities/problem/ui/DetailProblem.tsx
  src/features/submitCode/gitPush/ui/GitPushDialog.tsx
  src/features/submitCode/submission/ui/ProblemWorksSection.tsx
  src/shared/lib/codemirror/codeMirror.Docs.ts
  src/shared/mdx/MdxRenderer.tsx
Labels: fix

#125 fix : 페이지별 디자인 일괄 적용
  src/app/(auth)/(navigationsBarLayout)/@chatDialog/page.tsx
  src/app/(auth)/(navigationsBarLayout)/mypage/tab/ChangePassword.tsx
  src/app/(auth)/(navigationsBarLayout)/mypage/tab/Mine.tsx
  src/app/(auth)/(navigationsBarLayout)/notifications/page.tsx
  src/app/(auth)/(navigationsBarLayout)/problems/page.tsx
  src/app/(auth)/(navigationsBarLayout)/problems/ui/Table.tsx
  src/app/(auth)/(navigationsBarLayout)/rank/page.tsx
  src/features/auth/hooks/useLogin.ts
  src/features/chat/ui/chatRoomList/index.tsx
  src/shared/ui/select/Select.tsx
  src/widgets/NavigationBar/ui/AuthActions.tsx
  src/widgets/NavigationBar/ui/Notifications.tsx
Labels: fix, style, refactoring

#136 localstorage에 있는 git url 들고오는 코드 이슈 수정, 문제풀이 페이지 토론 정렬 방…
  src/features/discussions/disussions/ui/Discussions.tsx
Labels: fix, refactoring
