Repository ezcode-my/frontend, pull requests merged in 2025-08, with the labels that each got.

#59 refactoring : discussion 페이지 네이션, 정렬
  src/app/(auth)/(navigationsBarLayout)/page.tsx
  src/app/(auth)/(navigationsBarLayout)/problems/[problemId]/@tabs/page.tsx
  src/app/(auth)/(navigationsBarLayout)/problems/[problemId]/layout.tsx
  src/constants/paths.ts
  src/entities/discussions/discussions/model/query/discussion.query.type.ts
  src/entities/discussions/discussions/model/query/discussions.query.ts
  src/entities/discussions/index.ts
  src/features/discussions/DiscussionFooter.tsx
  src/features/discussions/disussions/ui/Discussion.tsx
  src/features/discussions/disussions/ui/DiscussionForm.tsx
  src/features/discussions/disussions/ui/Discussions.tsx
  src/features/discussions/reply/ui/NestedReply.tsx
  src/features/discussions/reply/ui/Replies.tsx
  src/features/discussions/reply/ui/Reply.tsx
  src/features/discussions/reply/ui/ReplyForm.tsx
  src/shared/types/pagenation.ts
  src/shared/ui/select/Select.tsx
  src/shared/ui/userProfile/UserImage.tsx
  src/shared/ui/userProfile/index.tsx
  src/widgets/NavigationBar/ui/AuthActions.tsx
Labels: refactoring

#60 refactor : coding test page
  src/entities/submitCode/submission/model/mutation/submitCode.mutation.ts
  src/features/submitCode/gitPush/hooks/useGitPush.ts
  src/features/submitCode/submission/hooks/useConnectProblemWebSocket.ts
  src/features/submitCode/submission/hooks/useSubscribeProblem.ts
  src/features/submitCode/submission/model/useProblemWebSocketStore.ts
  src/features/submitCode/submission/model/useProblemWebSocketStore.types.ts
  src/features/submitCode/submission/ui/TerminalOutput/CodeResultSummary.tsx
  src/features/submitCode/submission/ui/TerminalOutput/CodeReviewSummary.tsx
  src/features/submitCode/submission/ui/TerminalOutput/index.tsx
  src/features/submitCode/submission/ui/TerminalPanel.tsx
  src/shared/ui/LoginRequiredUi/RequireLoginDialog.tsx
Labels: refactoring

#58 Style/rank
  src/api/constants/api.constants.ts
  src/app/(auth)/(navigationsBarLayout)/rank/page.tsx
  src/entities/rank/query.ts
  src/entities/rank/types.ts
Labels: feat, style, refactoring

#70 fix : 접근권한 수정 및 로그인 모달 작업
  src/api/client/api.ts
  src/api/service/game/game.ts
  src/app/(auth)/(navigationsBarLayout)/game/_ui/CharacterIntro.tsx
  src/app/(auth)/(navigationsBarLayout)/game/_ui/CreateCharacter.tsx
  src/app/(auth)/(navigationsBarLayout)/game/_ui/tab/AdventureModal.tsx
  src/app/(auth)/(navigationsBarLayout)/game/_ui/tab/InventoriesModal.tsx
  src/app/(auth)/(navigationsBarLayout)/game/_ui/tab/ItemSkillModal.tsx
  src/app/(auth)/(navigationsBarLayout)/game/_ui/tab/PvpBattleModal.tsx
  src/app/(auth)/(navigationsBarLayout)/game/_ui/tab/PvpHistoryModal.tsx
  src/app/(auth)/(navigationsBarLayout)/game/_ui/tab/PvpMatchingModal.tsx
  src/app/(auth)/(navigationsBarLayout)/game/_ui/tab/SkillModal.tsx
  src/app/(auth)/(navigationsBarLayout)/game/_ui/tab/StatusModal.tsx
  src/app/(auth)/(navigationsBarLayout)/game/page.tsx
  src/app/(auth)/(navigationsBarLayout)/layout.tsx
  src/app/(auth)/(navigationsBarLayout)/problems/[problemId]/page.tsx
  src/app/(auth)/(navigationsBarLayout)/rank/page.tsx
  src/app/layout.tsx
  src/entities/game/model/query/game.query.ts
  src/entities/mypage/model/query.ts
  src/entities/rank/query.ts
  src/entities/submitCode/gitpush/actions/getGitHub.ts
  src/entities/submitCode/gitpush/model/query/gitpush.query.ts
  src/features/auth/hooks/useLogin.ts
  src/features/auth/hooks/useSignUp.ts
  src/features/auth/hooks/useSocialLogin.ts
  src/features/auth/store/authSlice.ts
  src/features/auth/ui/SignForm.tsx
  src/features/auth/ui/SignInSocialLogin.tsx
  src/features/auth/ui/SigninForm.tsx
  src/features/game/ui/GameModal.tsx
  src/lib/AuthGuard.tsx
  src/lib/AuthProvider.tsx
  src/middleware.ts
  src/shared/ui/LoginRequiredUi/RequireLoginDialog.tsx
  src/widgets/NavigationBar/navigateAttribute.ts
  src/widgets/NavigationBar/ui/AuthActions.tsx
  src/widgets/globalFloatingWidget/ui/index.tsx
Labels: refactoring

#73 fix : required login dialog
  src/app/(auth)/(navigationsBarLayout)/problems/[problemId]/page.tsx
  src/entities/auth/model/mutation/auth.mutation.ts
  src/entities/problem/api/server/getSubmitPrepareData.ts
  src/entities/problem/api/server/getSubmitPrepareData.type.ts
  src/entities/problem/index.ts
  src/entities/submitCode/submission/model/mutation/submitCode.mutation.ts
  src/entities/submitCode/submission/model/query/submitCode.query.ts
  src/entities/submitCode/submission/model/query/submitCode.query.type.ts
  src/features/discussions/disussions/model/Discussion.sort.context.tsx
  src/features/discussions/reply/ui/Replies.tsx
  src/features/submitCode/submission/hooks/useConnectProblemWebSocket.ts
  src/features/submitCode/submission/hooks/useSubscribeProblem.ts
  src/features/submitCode/submission/model/useProblemWebSocketStore.ts
  src/features/submitCode/submission/model/useProblemWebSocketStore.types.ts
  src/features/submitCode/submission/ui/ProblemWorksSection.tsx
  src/features/submitCode/submission/ui/TerminalOutput/CodeResultSummary.tsx
  src/features/submitCode/submission/ui/TerminalPanel.tsx
  src/lib/AuthGuard.tsx
  src/shared/ui/LoginRequiredUi/ProtectedBlurBox.tsx
  src/shared/ui/LoginRequiredUi/RequireLoginDialog.tsx
  src/widgets/NavigationBar/ui/AuthActions.tsx
Labels: fix, refactoring

#81 fix : githubUrl 파라미터를 useGetGitHubRepo 및 useAutoGitPushStatus에 추가하여 유무에 따라 enabled 처리
  src/entities/submitCode/gitpush/model/query/gitpush.query.ts
  src/features/submitCode/gitPush/hooks/useGitPush.ts
  src/features/submitCode/gitPush/ui/GitPushDialog.tsx
Labels: fix

#88 fix : chat 관련 웹소켓 로직 수정
  src/app/(auth)/(navigationsBarLayout)/@chatDialog/page.tsx
  src/features/chat/hooks/socket/useJoinChatRoom.ts
  src/features/chat/hooks/socket/useLeaveChatRoom.ts
  src/features/chat/hooks/socket/useSubChatRooms.ts
  src/features/chat/hooks/useChatDialogTrigger.ts
  src/features/chat/hooks/useChatMessage.ts
  src/features/chat/model/useChatWebSocketStore.ts
  src/features/chat/model/useChatWebSocketStore.types.ts
  src/features/chat/types/index.ts
  src/features/chat/ui/chatMessage/ChatMessage.tsx
  src/features/chat/ui/chatMessage/SystemMessage.tsx
  src/features/chat/ui/chatRoom/ChatInput.tsx
  src/features/chat/ui/chatRoom/index.tsx
  src/features/chat/ui/chatRoomList/ChatRoomItem.tsx
  src/features/chat/ui/chatRoomList/index.tsx
  src/features/submitCode/submission/hooks/useSubmitForReview.ts
  src/features/submitCode/submission/hooks/useSubscribeProblem.ts
  src/lib/AuthGuard.tsx
  src/shared/util/formatDate.ts
Labels: fix, refactoring

#90 fix : 랜딩페이지에서만 채팅 모달이 팝업되는 문제 해결
  src/app/(auth)/(navigationsBarLayout)/@chatDialog/page.tsx
Labels: refactoring

#91 refactoring : problem description
  src/entities/problem/api/server/getDetailProblem.type.ts
  src/entities/problem/ui/DetailProblem.tsx
Labels: style, refactoring

#97 feat : Image input 컴포넌트
  next.config.ts
  public/icons/upload.svg
  src/app/globals.css
  src/app/testinput/page.tsx
  src/shared/ui/InputFiled/ImageTypeFiled.tsx
  src/shared/ui/InputFiled/InputTypeFiled.tsx
  src/shared/ui/InputFiled/imageTypeFiled/RenderImageContent.tsx
  src/shared/ui/InputFiled/imageTypeFiled/WrapperImageInput.tsx
  src/shared/ui/InputFiled/imageTypeFiled/index.tsx
  src/shared/ui/InputFiled/index.tsx
Labels: feat

#98 Feat : discussion report
  src/api/constants/api.constants.ts
  src/features/discussions/DiscussionDropDown.tsx
  src/features/discussions/DiscussionFooter.tsx
  src/features/discussions/disussions/ui/Discussion.tsx
  src/features/discussions/mutation/report.mutation.ts
  src/features/discussions/reply/ui/NestedReply.tsx
  src/features/discussions/reply/ui/Reply.tsx
  src/features/report/report.types.ts
  src/shared/ui/modals/CreateReportModal/CreateReportModal.tsx
Labels: feat

#100 chore : EZ-CODE 브랜드 이름 통일을 위한 텍스트 수정 , 파비콘 변경
  public/favicon.ico
  public/favicon.svg
  src/app/(auth)/(navigationsBarLayout)/rank/page.tsx
  src/app/(guest)/layout.tsx
  src/app/layout.tsx
  src/entities/rank/ui/HomePageRanking.tsx
  src/widgets/NavigationBar/navigateAttribute.ts
Labels: chore, style

#101 feat: 이미지 제거 기능 추가 및 WrapperImageInput 컴포넌트 수정
  src/shared/ui/InputFiled/imageTypeFiled/WrapperImageInput.tsx
  src/shared/ui/InputFiled/imageTypeFiled/index.tsx
Labels: feat
